### ISSUE TITLE
Finding bundle locally?

### ISSUE THREAD

**Issue by jpfiorilla** [rafrex/spa-github-pages#14]
Hi Rafael,

Firstly thanks for making this resource!

I'm trying to test the site locally so I'll run `npm start` & open the html file and it won't find the bundle.js file:

GET file:///build/bundle.js net::ERR_FILE_NOT_FOUND               index.html:94

It works fine on my github page domain (johnfiorilla.website). Can you offer some instruction on how to do this? Pretty new to webpack & stuff so I'd appreciate it! Thanks!

**Comment by rafgraph** [comment]
You need access the `index.html` from the server (in this case `webpack-dev-server`), the default is `http://localhost:8080`, or the scripts won't load. I just added a note to the readme about this.
