### ISSUE TITLE
Warning: [react-router] Location "/repo-name/" did not match any routes

### ISSUE THREAD

**Issue by goldylucks** [rafrex/spa-github-pages#15]
Thanks a lot for this project!
now if I could only get it to work ;)

I have a react SPA hosted on gh pages, and I have two repos for it:
1. "original": Used for dev ([repo]((https://github.com/goldylucks/memory-n-back))) and hosting the production app on gh-pages
2. "staging": used only for hosting the [staging app]((https://goldylucks.github.io/memory-n-back-staging/)) on [gh-pages branch](https://github.com/goldylucks/memory-n-back-staging/commit/aa9d9ba78a773f7f0cf4785bc59c1c9bed8633da)

I've bundled and deployed [this commit](https://github.com/goldylucks/memory-n-back/commit/2f98462d34af8b898d7590244ece9e2dc7565cfd) from repo 1 to staging repo gh-branch.

tho when I go to `https://goldylucks.github.io/memory-n-back-staging/` I get in the console `Warning: [react-router] Location "/memory-n-back-staging/" did not match any routes`

I've copied the [404.html](https://github.com/goldylucks/memory-n-yoru sback-staging/blob/gh-pages/404.html) like u said, and tried setting [pathPrefix](https://github.com/goldylucks/memory-n-back-staging/blob/gh-pages/404.html#L24) to both false/true

Also I copy pasted the [script](https://github.com/goldylucks/memory-n-back-staging/blob/gh-pages/index.html#L11) to the `index.js` (before the call to the [spa bundle](https://github.com/goldylucks/memory-n-back-staging/blob/gh-pages/index.html#L45))

If it matters for any reason, I also have react-native and a nodejs a server code on that repo, tho to gh-pages only the react app and relevant assets are deployed

That's all the information I can think of that is relevant

any ideas what I'm missing?

Thanks again for this project and sry if I'm missing something really dumb :hankey:

**Comment by rafgraph** [comment]
This is an issue with how you set up your routes. React Router works based on the full absolute path, so you need to add the repo-name prefix to your routes and links, for example:
`<Route path="/memory-n-back-staging/about" component={About} />`
`<Link to="/memory-n-back-staging/about">About</Link>`

Also, you should set `pathPrefix` to true for the redirect to work.

**Comment by goldylucks** [comment]
gotcha, sry for wrongfully opening the issue

did u ever get it to work with non custom domain gh-pages ?

**Comment by goldylucks** [comment]
btw I'm trying this with the same website just hosted on surge and it also doesn't work. u c any reason it won't work on surge?

EDIT: it DOES work with surge!
might wanna add it to the readme? :)

Maybe call this project static-spa or something.
It might (probably?) work with firebase or similar static hosting solutions as well

**Comment by rafgraph** [comment]
Yes it works fine with non custom domains for gh-pages, you just have to prefix Routes and Links with the repo name and set `pathPrefix` to true.

**Comment by goldylucks** [comment]
>Yes it works fine with non custom domains for gh-pages, you just have to prefix Routes and Links with the repo name and set pathPrefix to true.

r u monkey-patching the `<Route>` and `<Link>` for this?
or passing a constant to all of them i.e. 

```js
// routes.js
import { GH_PAGES_PREFIX } from 'path/to/constants'
<Route path={ `${GH_PAGES_PREFIX}/mypath` } component={ MyComponent }>

// constants.js
export const GH_PAGES_PREFIX = isProd ? 'repo-name' : ''
```

**Comment by rafgraph** [comment]
Not monkey patching. Just using a `repo-name` constant.

**Comment by balthazar** [comment]
You can also use the `basename` option when creating your history, so you don't have to do this.
