### ISSUE TITLE
Still cannot load my page in github pages 

### ISSUE THREAD

**Issue by ptchiangchloe** [rafrex/spa-github-pages#17]
Hi 

I got confused about your instructions with setting up 404.html in build folder. Every time I run npm build, the 404.html will be gone. I can load my page in 
https://ptchiangchloe.github.io/portfolio-site/#/, 
but every time I redirect my page, it will turn into 404 such as https://ptchiangchloe.github.io/#/art
so I need to manually add https://ptchiangchloe.github.io/portfolio-site/#/art in order to rendering.

Also, my custom URL doesn't work either. Here is my [repo ](https://github.com/ptchiangchloe/portfolio-site)

Thanks,

Hanyu

**Comment by rafgraph** [comment]
Don't put 404.html in the build directory. This repo runs the live demo site - use its structure as a reference.

**Comment by ptchiangchloe** [comment]
Hi 

Sorry, I changed it and I still have the same problem, I'm thinking maybe this is not working? 

Thanks

**Comment by rafgraph** [comment]
Nope, the example site works fine. Issue is on your end.

Read the GitHub docs https://help.github.com/categories/github-pages-basics/ the instructions here are not a substitute for the github docs.

My suggestion would be to clone this repo and follow the detailed instructions to get the example site working with your account before making any changes to the code and content.

**Comment by ptchiangchloe** [comment]
I'm not saying your app doesn't work, however, your code is not working my app, since I got 404 from Github and the same error before I add your code.

**Comment by rafgraph** [comment]
It sounds like you're having an issue with loading a custom 404 page.
https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/

Make sure `404.html` is present in the root of the branch that is being served by GitHub pages, which in your case should be the `gh-pages` branch - that's where GitHub pages will look for a custom 404 page, if it doesn't find it it will serve it's standard 404 page, which I think is what's happening.

**Comment by rafgraph** [comment]
Also, if you're using it with a project pages site without a custom domain, i.e. https://ptchiangchloe.github.io/portfolio-site, make sure to set `segmentCount = 1` [here](https://github.com/rafrex/spa-github-pages/blob/gh-pages/404.html#L26) so `/portfolio-site` will remain in the path after the redirect.

**Comment by rafgraph** [comment]
It looks like you're using the gh-pages npm package to create your gh-pages branch from your master branch. In this case you need to have the 404 file in the public directory on your master branch so it ends up in the root of your gh-pages branch.

For someone who is starting out my suggestion would be to use as little tooling as possible to really understand what's happening so you don't run into issues like this one, and then slowly add more tooling. That is, just create your site in the gh-pages branch and not use the gh-pages npm package. Tooling is great, but can cause a lot of frustrating issues if you're a beginner and don't understand what it's doing.
