### ISSUE TITLE
Can't Find bundle.js

### ISSUE THREAD

**Issue by ethanshar** [rafrex/spa-github-pages#18]
Hey There,
I tried your solution but for some reason the index.html can't find the bundle.js.
not sure if it's a path thing.
I'm using the default domain of my repo
my src path directs to "/repo-name/build/bundle"
also copied the script and the 404 page and change the segmentCount to 1.

Locally everything works fine but the bundle served differently obviously.. 
any idea what might be missing ?

**Comment by rafgraph** [comment]
It sounds like a path problem, but it's hard to tell without seeing the code.
