### ISSUE TITLE
My page is empty!!!

### ISSUE THREAD

**Issue by Amahmoud1994** [rafrex/spa-github-pages#19]
I did all the steps provided and I got the domain working " http://abdelrahman-mahmoud.me/ " but the page has no content. When I run *npm start* it works on my local machine but when I open the index.html page alone it doesn't work!!! 
.
.
Any suggestions ??!!

**Comment by rafgraph** [comment]
Opening index.html directly in a browser won't load the scripts - it must be served from a sever.

**Comment by Amahmoud1994** [comment]
What about the domain?

**Comment by rafgraph** [comment]
Sorry, couldn't say without seeing your code.

**Comment by Amahmoud1994** [comment]
The error in the console says  *Failed to load resource: the server responded with a status of 404 (Not Found)*  and *http://abdelrahman-mahmoud.me/build/bundle.js* file is not found!!!

**Comment by rafgraph** [comment]
Make sure `build/bundle.js` is committed and pushed to your repository (run `$ npm run build` to create it). Other than that it could be any number of things. Ask a friend to look at your code.
