### ISSUE TITLE
index.html is not redirecting to route

### ISSUE THREAD

**Issue by shamdasani** [rafrex/spa-github-pages#23]
Hello,

My site https://shamdasani.org ([github](https://github.com/shamdasani/shamdasani.github.io)) is not redirecting the blog post urls on refresh.

here is an url that goes back to the homepage, but does not redirect: https://shamdasani.org/hello-world

all there is a `?p=/hello-world` in the domain 

Would appreciate any help. Thanks!

**Comment by rafgraph** [comment]
You have to add this script to `index.html`, https://github.com/rafrex/spa-github-pages/blob/gh-pages/index.html#L58
