### ISSUE TITLE
Github pages served from master branch /docs without custom domain

### ISSUE THREAD

**Issue by mcauser** [rafrex/spa-github-pages#25]
Changes to run this as a **Project Page** served from the **/docs folder** on the **master branch**:
eg. http://username.github.io/spa

* Create "spa" repository on your GitHub account. Rename all "spa" occurrences below if you call it something else.
* Clone git@github.com:rafrex/spa-github-pages.git
* Remove the `.git` folder.
* Delete the `CNAME` file
* Create `/docs` folder in the root.
* Move `index.html`, `404.html` and `/build` into `/docs`

/docs/404.html
```
var segmentCount = 1;
```

/docs/index.html
```
<script src="/spa/build/bundle.js"></script>
```

/src/index.js
```
<BrowserRouter basename="/spa">
```

/package.json
```
"start": "webpack-dev-server --devtool eval-source-map --content-base docs/ --history-api-fallback --open --openPage spa/",
```

/webpack.config.js
```
output: {
  path: `${__dirname}/docs/build`,
  publicPath: '/spa/build/',
  filename: 'bundle.js',
},
```

Install React and dependencies. Build and start the webpack dev server.
```
npm install
npm run build
npm start
```
Opens: http://localhost:8080/spa/

Instantiate the repository and push to GitHub
```
git init
git add .
git init
git commit -m "first commit"
git remote add origin git@github.com:username/spa.git
git push -u origin master
```

* Open the Settings page on GitHub
* Choose GitHub Pages Source **master branch /docs folder** and Save
* In a few minutes, open http://username.github.io/spa

**Comment by ackernaut** [comment]
👏 this helps a lot!

**Comment by cadenzah** [comment]
Setting `basename` props in `<BrowserRouter />` is the key point of this.

**Comment by rafgraph** [comment]
Thanks for this. I added a section to the readme on how to use the `/docs` folder for the build and the root `/` for the source code.
