### ISSUE TITLE
Contribute to translate into various languages: Korean

### ISSUE THREAD

**Issue by sujinleeme** [rafrex/spa-github-pages#26]
Hello, @rafrex.
Your elegant solution was really helpful for me to deploy my react apps. Though I haven't asked permission about translation, but I translated your repo  into Korean Language about a week ago and I'd like to share it. You can visit [korean translation ver.](https://github.com/sujinleeme/spa-github-pages-ko) 

Thanks, 
Sujin

**Comment by rafgraph** [comment]
Great, thanks for letting me know!
