### ISSUE TITLE
Static site generation for SEO

### ISSUE THREAD

**Issue by baohouse** [rafrex/spa-github-pages#27]
In case you want your site to be SEO-friendly, the site might benefit from being generated into a static site. 🤔

I found https://github.com/phenomic/phenomic to be an interesting candidate, but it will take me some time to figure out the nuts and bolts of integration with spa-github-pages.

**Comment by rafgraph** [comment]
Static site generation is out of scope for this project. Gatsby is a great solution for generating static sites - see https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/
