### ISSUE TITLE
Implement a development environment

### ISSUE THREAD

**Issue by yannbertrand** [rafrex/spa-github-pages#3]
It's quite boring to push each time we want to try a new feature.

It is surely easy to implement a simple HTTP server to allow users to develop their website on a local environment. Hot reload would also be really interesting.

I will probably do a PR to show you what I mean by that.

What do you think of the idea?

**Comment by rafgraph** [comment]
My intention was not for people to `$ git push` to test out each change, but only for changes they want to make live. It is essentially bring you own dev environment. I should've been more clear about that in the documentation.

Everyone has their preferred dev environment they like to use, so in general I'm not a fan of forcing it on the user. While including one would make it easier to use for someone who uses the same setup, it also makes the project more complex for someone who is not familiar with the included dev setup.

That said, I'm not totally against it as long as it is well documented for 1) how the included dev setup works (not just `$ npm start`, but explain what that does in this project), and 2) how to use this with your own setup (`$ webpack -d --watch` and serve `index.html` and `404.html` for 404s).

**Comment by rafgraph** [comment]
I created a `dev-environment` branch with my preferred setup. Check it out `$ npm start`. It just runs `webpack -d --watch` and `live-server --entry-file=404.html`. `live-server` does live reloading of all assets - `bundle.js`, `app.css`, etc... The `--entry-file=404.html` will serve `404.html` when the requested file can't be found so it mimics how gh-pages works. (Normally I would set `--entry-file=index.html` which is how servers that support single page apps work - and what I wish gh-pages would do).

I haven't looked into webpack dev server with hot module replacement. What would the advantages be over the `live-server` setup? Sometimes it feels a little slow as it has to re-run `webpack -d` each time - would the dev server with HMR be faster? One nice thing about `live-server` is it live reloads changes to css files, can the webpack dev server do that?

**Comment by zklinger2000** [comment]
I'd love to see your setup @YannBertrand as a walkthrough!  Sounds like a great article to me.  I'm just about to sit down and try to setup webpack for the first time.

**Comment by yannbertrand** [comment]
You're right, I totally agree @rafrex, the library should stay as modular as possible.

However, for people like @zklinger2000 and me it would be really interesting to know that it is that simple to add an auto-refreshed dev server when you don't necessarily got the backend knowledge to do it yourself 😄 . A walkthrough section in the readme could be neat! In fact, I didn't know a lot about webpack, that's why I used hapi at first and webpack-dev-server afterwards (I kind of struggled with it when your config is really simple!).

I didn't manage to get HMR working though. It would be convenient to add it in the example.

Thanks for your example in the branch, I will definitely use it the way you do!
