### ISSUE TITLE
Why don't just make 404.html a copy of index.html?

### ISSUE THREAD

**Issue by bpceee** [rafrex/spa-github-pages#30]
Brilliant! 
But making 404.html a copy of index.html also works. 
What's the benefits of this repo?  SEO friendly?
Did I miss something?

**Comment by LittleClown** [comment]
I also think so

**Comment by johnss** [comment]
Quoted from readme.md
>A quick SEO note - while it's never good to have a 404 response, it appears based on Search Engine Land's testing that Google's crawler will treat the JavaScript window.location redirect in the 404.html file the same as a 301 redirect for its indexing. From my testing I can confirm that Google will index all pages without issue, the only caveat is that the redirect query is what Google indexes as the url. For example, the url example.tld/about will get indexed as example.tld/?p=/about. When the user clicks on the search result, the url will change back to example.tld/about once the site loads.


404.html is intended to be used for not found error not for routing  SPA so it will return 404 and search engine usually will not index error page (4xx & 5xx), but will crawl, follow redirect and indexing the redirected pages if not returning error response header, 404.html using window.location for redirecting to actual page without 404 response header

**Comment by bpceee** [comment]
@johnss Thanks a lot! Good to know.
