### ISSUE TITLE
Query params are garbled

### ISSUE THREAD

**Issue by hyvyys** [rafrex/spa-github-pages#33]
The following URL with query:

```
http://localhost:8080/search?lang=English&q=abc&w=def&f=0101111100&p=10
```

is transformed into this:

```
http://localhost:8080/searc10?abc
```

I see that the script references `q` and `p` params of the query. Are these parameter names somehow reserved, beyond the scope of this script? Are they some params appended by GitHub?

**Comment by rafgraph** [comment]
v6 no longer relies on `q` and `p` in the query, so this issue should be fixed. Please use the latest version of the redirect scripts in `index.html` and `404.html`.
