### ISSUE TITLE
Google fail to index

### ISSUE THREAD

**Issue by johnss** [rafrex/spa-github-pages#35]
seems google changed how it index javascript, you can search it using "site:spa-github-pages.raflex.com", it only index home page, in the past it return many result (home dir and its some child directory)

i dont know why, but docute still works, try "site:docute.org" without quote.

**Comment by mittalabhas1** [comment]
I'm facing a similar issue @rafrex. Do you have any solution in mind that we can work on?
![image](https://user-images.githubusercontent.com/3685585/85588592-71c3e280-b660-11ea-98ba-8c14b7d3acf0.png)

**Comment by Salil-Jain** [comment]
Hi @mittalabhas1, were you able to solve the indexing issue?

**Comment by rafgraph** [comment]
Unfortunately there is no good solution to this. The best I could come with is to create a `sitemap.txt` to inform crawlers of the pages on the site (the sitemap needs to contain the redirect links). I added info on this to the readme, please see https://github.com/rafgraph/spa-github-pages#seo. Note that the [sitemap link generator](https://spa-github-pages.rafgraph.dev/sitemap-link-generator) is for the most recent version of the redirect scripts (v6), so be sure to update the scripts in `index.html` and `404.html` before using the sitemap link generator.

**Comment by Salil-Jain** [comment]
Thanks. I'll try that out.
