### ISSUE TITLE
Google search result contains "You need to enable JavaScript to run this app" in description

### ISSUE THREAD

**Issue by eddex** [rafrex/spa-github-pages#43]
Hi

Thanks for this workaround. It works great for the page I recently created (https://jackfruit.games).

However, when I search for the page on google, I can see that in the description of the page, the error message "You need to enable JavaScript to run this app" is shown.

![image](https://user-images.githubusercontent.com/5302085/98581002-1fa6f500-22c1-11eb-8cbf-c060a22ae733.png)
(Yes, I need to update the description of the main page too 🙃)

The code for the page can be found here: https://github.com/jackfruitgames/jackfruit.games/blob/main/src/components/MarkdownContentPage.js

Any idea why this happens and how I can fix this?

**Comment by rafgraph** [comment]
Not sure why this is happening, but it seems doubtful that it is because of the `spa-github-pages` script.

**Comment by rafgraph** [comment]
I also am not able to reproduce the issue when I search on google https://www.google.com/search?q=site%3Ajackfruit.games

<img width="717" alt="Screen Shot 2020-11-11 at 4 53 01 PM" src="https://user-images.githubusercontent.com/11911299/98868630-7128be80-243e-11eb-926d-5d0649765226.png">
