### ISSUE TITLE
about.html

### ISSUE THREAD

**Issue by pickypg** [rafrex/spa-github-pages#46]
It looks like GitHub now reserves the "about" path for itself, so it's necessary to copy `404.html` to also be `about.html`.

Thanks for this example repository; it was incredibly helpful.

**Comment by rafgraph** [comment]
It seems to work fine, do you have a failing example?

This loads the spa:
https://spa-github-pages.rafgraph.dev/about

**Comment by pickypg** [comment]
https://github.com/earleatlaw/earleatlaw.github.io/commit/5ef8c2bc2e3fcaca74c122a764b11aea331a2ebb

I needed to add it here. I can remove it to show you the impact. I wonder if yours works because it has not been rebuilt in 5 months.

**Comment by rafgraph** [comment]
I just created a new build, and no issues. So I don't think that's it. Maybe it has to do with that you're serving out of the `/docs` folder? What happens for you when `about.html` doesn't exist?

**Comment by pickypg** [comment]
It was displaying the the GitHub Pages 404 result (like this https://elastic.github.io/eui/fake). For some reason it was the only page doing it (that I could find by guessing other common page names).

However, now that I have added (https://github.com/earleatlaw/earleatlaw.github.io/commit/5ef8c2bc2e3fcaca74c122a764b11aea331a2ebb) and removed (https://github.com/earleatlaw/earleatlaw.github.io/commit/5849afcd917486d44a65f947b22fc1022280ef75) it, it seems to be working perfectly without it.

I guess we can close this one out and sorry for the random noise. I'll let you know if it reappears.
