### ISSUE TITLE
No longer working for SEO purposes?

### ISSUE THREAD

**Issue by jhildenbiddle** [rafrex/spa-github-pages#55]
It appears this approach no longer works for SEO purposes.

<img width="705" alt="CleanShot 2022-01-02 at 09 21 40@2x" src="https://user-images.githubusercontent.com/442527/147880398-afe4e9a5-1226-442b-8fd1-cf813808c9aa.png">

**Comment by rafgraph** [comment]
No it still works, the second link in your screenshot is for https://spa-github-pages.rafgraph.dev/?/sitemap-link-generator, so the pages in the sitemap are still discoverable to google. Google will omit pages from search results for other reasons (duplicate, not important etc), which is probably happening to the example and example two deep pages. I just tried it and for me it pulls up the example page as well.
<img width="1126" alt="Screen Shot 2022-01-02 at 10 30 35 AM" src="https://user-images.githubusercontent.com/11911299/147880840-09727efd-0a44-4e30-8de2-75153bf41533.png">

**Comment by jhildenbiddle** [comment]
Yep. True enough. Interestingly, when I revisit the same URL in google I now see the example page also. 🤷‍♂️ 

Thanks, @rafgraph.
