### ISSUE TITLE
['] being converted to [%27] and breaking React Router

### ISSUE THREAD

**Issue by Aarnavv** [rafrex/spa-github-pages#56]
Hey! Thanks a lot for the code. It seems to be working fine for the most parts but when the URL has " ' " in it, for example, 
```
/editions/august'21-edition
```
it is being converted to 
```
/editions/august%2721-edition
```
which is breaking the link.

Since I am using React Router,
```
      <Route path="/editions/august'21-edition" element={<><Publication edition={2} /></>} />
```
it is breaking the website.

You can view this issue yourself at https://the-innominate-newsletter.github.io/
You can try to click on any one of the cards and then try to refresh the page and you will see what I am talking about. 

Thank you for taking the time to read this and helping me out!

**Comment by rafgraph** [comment]
Hi, apostrophes `'` aren't valid characters to use in a url. The browser is automatically encoding the `'` to `%27` when it's part of the query string.
