### ISSUE TITLE
Images not rendering to website

### ISSUE THREAD

**Issue by johannaperez** [rafrex/spa-github-pages#9]
Thanks for this repo! My app is up and running correctly except for the static images.  I see them in the build, but dont understand why they are not rendering to the website.  Are static images not supported?

**Comment by rafgraph** [comment]
This is not a `spa-github-pages` issue. This is most likely a path issue with how you are accessing your images.

Instead of: `<img src={require('../images/condor.png')} />`,
try: `<img src="/images/condor.png" />`

**Comment by johannaperez** [comment]
Oh great thank you!
